### ISSUE TITLE
HueRLGenerator.lightsIndexState hardcoded to a value of 2

### ISSUE THREAD

**Issue by NSBrianWard** [yoannfleurydev/discord-hue#1]
In **src/action/message/HueTurn.ts**, round about line 25 there's some indication that we're only able to manipulate lights at index 2 right now. Is that correct?

I've verified via direct PUT requests that the URL works, but I'm not able to change a light at say index 9 without directly changing the index that's hardcoded in. I verified that also and was able to then make **hue turn on** work via Discord.

I'm assuming that additional work is still needed to gather the index specified from the message based on the name and then pass that into the URL that's getting constructed.

Cool project!

**Comment by yoannfleurydev** [comment]
Hi, thanks for your interest in that project. :smiley: 

> In src/action/message/HueTurn.ts, round about line 25 there's some indication that we're only able to manipulate lights at index 2 right now. Is that correct?

Correct, this index matches the light that was in front of me when I started the project, so it was easier for me to set an hard-coded value to check if the code worked.

> I'm assuming that additional work is still needed to gather the index specified from the message based on the name and then pass that into the URL that's getting constructed.

Yes, I'm thinking of multiple ways to select the light like:

* `hue turn Kitchen [on|off]` that will match the `name` attribute without case sensitivity (and probably later with an enhanced pattern matching: ktchen will work for Kitchen)
* `hue turn 1 [on|off]` that will match the index of the light.
* `hue turn 00:17:88:01:00:bd:c7:b9-0b [on|off]` that will match the `uniqueid` attribute

Now, assuming that if I have a light with `name: "3"` on **index 2**, and a light with `name: "Kitchen"` on **index 3**, `hue turn 3 on` will turn on the first one :bulb:. The priority will be on the name.

What do you think about these rules?

**Comment by yoannfleurydev** [comment]
I have open 3 new sub issues for this feature request to split the tasks.

1. [`hue turn [light name] [on|off]`](https://github.com/yoannfleurydev/discord-hue/issues/2)
2. [`hue turn 1 [on|off]`](https://github.com/yoannfleurydev/discord-hue/issues/3)
3. [`hue turn 00:17:88:01:00:bd:c7:b9-0b [on|off]`](https://github.com/yoannfleurydev/discord-hue/issues/4)

The first one (the important one), is done. You can now enjoy turning light on and off with the name. Also, I have added a more silent response from the bot as I was annoyed with notification from my other devices. It will now respond with a reaction on discord, not with a message.

![image](https://user-images.githubusercontent.com/3920615/59550511-ba37c300-8f6b-11e9-8352-070699c88cc9.png)

I'm closing this issue. Thanks again for the report. 😃

**Comment by NSBrianWard** [comment]
Yeah, that sounds great!
